### ISSUE TITLE
error 500 luego de registración vía google auth 

### ISSUE THREAD

**Issue by mabeett** [eventoL/eventoL#210]
el sistema da error 500 luego de haberme registrado validando a mi usuario google auth.

**Comment by mabeett** [comment]
Borré las cookies del sitio, me intenté loguear invocando mi cuenta de google y ahora veo el panel.

**Comment by reyiyo** [comment]
No lo pudimos reproducir. Si vuelve a suceder lo reabrimos :)

**Comment by reyiyo** [comment]
Gracias por los pasos!

Justo ahora no tenemos para probar, pero ya estamos trabajando en la versión que se va a usar este año. Reabro el issue así lo probamos cuando tengamos la instancia de prueba para este año!
