### ISSUE TITLE
link a email en evento se valida carga como foo@bar.tld pero se genera mail link

### ISSUE THREAD

**Issue by mabeett** [eventoL/eventoL#255]
En editar evento, Dónde puede seguir tu evento la gente? No se permite en el formulario cargar el texto mailto:foo@example.org, pero sí foo@example.org.
En la portada del evento al final la url que se genera es

https://raiz/event/nombre/foo@example.org

**Comment by HacKanCuBa** [comment]
Hola @mabeett! Podrías verificar si en la release actual el problema persiste?
Saludos!

**Comment by HacKanCuBa** [comment]
Ya encontré el problema, corregido

**Comment by HacKanCuBa** [comment]
Persiste
