### ISSUE TITLE
Verificar subida de archivos

### ISSUE THREAD

**Issue by HacKanCuBa** [eventoL/eventoL#270]
Aparentemente, la subida tiene inconvenientes. Debería servir para guardar presentaciones y videos y luego servilas a los visitantes.

**Comment by HacKanCuBa** [comment]
El problema se da en la subida de archivos grandes (1.5M+), debe incrementarse el tamaño permitido en nginx

**Comment by FedeG** [comment]
Los archivos se suben pero si pesan mucho (mas de 20mb) el request se corta.
