### ISSUE TITLE
Soportar historico con /uid o /id

### ISSUE THREAD

**Issue by FedeG** [eventoL/eventoL#272]
- [x] Usar un uid o el id en lugar del event_slug
- [x] Hacer las busquedas en la pagina principal solo para eventos futuros.
- [x] Poder tener acceso a eventos pasados.
<del>- [ ] Hacer un buscador para eventos pasados.</del>

**Comment by HacKanCuBa** [comment]
See branch [`issue-272`](https://github.com/eventoL/eventoL/tree/issue-272)

**Comment by HacKanCuBa** [comment]
Voy a separar lo del buscador para eventos pasados en otro issue, así podemos cerrar el actual
