### ISSUE TITLE
Mint x64 no figura en listado de distribuciones instaladas

### ISSUE THREAD

**Issue by fefulowe** [eventoL/eventoL#285]
En la lista desplegable de Submit Installation, en el campo Software no figura la distribución Mint x64 en la lista desplegable (figura solamente Mint x86).

Faltaría un campo "Otro" en el listado.

Tampoco se puede establecer el contenido manualmente.

**Comment by FedeG** [comment]
Voy a agregar "Mint x64" y la opción de "Otro" a la lista predeterminada.
Esa lista igual tiene un abm en /admin para que los organizadores puedan agregar si es que falta alguno.

**Comment by FedeG** [comment]
@fefulowe en realidad estan las dos opciones actualmente:
Mint x64: https://github.com/eventoL/eventoL/blob/master/eventol/manager/initial_data/software.json#L44
Otro: https://github.com/eventoL/eventoL/blob/master/eventol/manager/initial_data/software.json#L100

Hay un problema en la busqueda, la barra esa es un autocomplete que trae 5 opciones pero si escribís ahora tiene un fallo.

**Comment by FedeG** [comment]
Esta issue se va a cerrar porque lo que pide es algo que esta, pero queda linkeada al bug del autocomplete.
