### ISSUE TITLE
Mostrar eventos en los que el usuario se encuentra registrado

### ISSUE THREAD

**Issue by HacKanCuBa** [eventoL/eventoL#286]
Una vez registrado a un evento, no hay forma de ver a qué eventos uno se registró.
Mostrar los eventos en el perfil de usuario, e indicar si es asistente, colaborador y/o instalador (capaz bootstrap badges?)

**Comment by FedeG** [comment]
Si, esa idea también la tenia en mente pero no lo había puesto en una issue.
Mi idea era poner en el index una opción "Mi lista" o directamente un slider "Eventos en los que participo/e" con los eventos en donde tengo alguna participación (asistente, colaborador, organizador, ...)
