### ISSUE TITLE
Registro como asistente: no pedir datos existentes

### ISSUE THREAD

**Issue by HacKanCuBa** [eventoL/eventoL#287]
Con la sesión iniciada, al tratar de registrarse como asistente se vuelve a solicitar datos como nombre, apellido, email, etc que ya fueron provistos al sistema. No tiene sentido, e incluso causaría que que se tengan datos distintos!
Pre completar esos campos con los datos existentes y marcarlos como readonly.

**Comment by FedeG** [comment]
Eso seria esta issue directamente: #273
Ya que en realidad ni tendría que pedirte datos mas que si vas a instalarte algo, ya que el resto los tiene de te usuario.
