### ISSUE TITLE
Tunning de características al crear un evento

### ISSUE THREAD

**Issue by HacKanCuBa** [eventoL/eventoL#289]
Al crear un evento, incluir checkboxes para marcar si se van a tener instaladores o colaboradores. p.e., un evento que no requiere colaboradores ni asistentes, como una Jam, desmarcaría estas casillas.

**Comment by FedeG** [comment]
Si, esa es una de las ideas que teníamos hace ya tiempo en Eventol.
La rapida es poner eso check y simplemente agregar algun tag en las template de django para que no muestre las cosas que no hiciste check.
Igual por ejemplo hoy en dia el asistente tiene un campo indicando si va a instalarse algo y eso solo pararía en un install fest.
