### ISSUE TITLE
Tickets: utilizar una cifra aleatoria

### ISSUE THREAD

**Issue by HacKanCuBa** [eventoL/eventoL#291]
Considero que sería más conveniente utilizar una cifra aleatoria para generar el "nro" de ticket, en lugar de un número literal que permite que cualquier asistente impersone a otro (más allá de que esto no nos representa un problema grave, sí es molesto y no veo correcto).
Asimismo, el QR del ticket no indica a qué evento pertenece, así que puede ser usado con cualquier evento!

21 caracteres alfanuméricos equivaldrían a los 36 de un UUID4 del event_uid (y es más corto). Otra opción podría ser un KDF del event_uid representado con base64, pero podría consumir más recursos innecesariamente.

**Comment by HacKanCuBa** [comment]
Opinión @FedeG ?

**Comment by FedeG** [comment]
Si bien hoy en día no es un problema grave, si en un futuro los tickets tuvieran cupo, precio o algo que le hiciera tener valor si lo seria.
Pondría los caracteres alfanuméricos como en el caso del event_uid.

**Comment by HacKanCuBa** [comment]
Avalo, aunque usuaría algo alfanumérico más corto que el event_uid, q es UUID4 y es hexa, incómodo si se necesitace tipear.
Es trivial implementarlo igual:
```python3
from secrets import choice
from string import digits, ascii_lowercase, ascii_uppercase
chars = digits + ascii_lowercase + ascii_uppercase
len = 21
passwd = ''.join([choice(chars) for _ in range(len)])
```

lo escribí de galerazo, puede que tenga algún typo

**Comment by HacKanCuBa** [comment]
Probado OK
