### ISSUE TITLE
Crear organizaciones/comunidades/metaeventos

### ISSUE THREAD

**Issue by FedeG** [eventoL/eventoL#359]
El home del `/event/<slug>` tiene que poder ser editable (imagen de fondo, logo y texto) y el slug pasar a ser un nuevo modelo (algo como `metaevento`)

**Comment by gilgamezh** [comment]
nuevas urls:

- Event: `/event/human_slug` (requiere migración)
- EventTag: `/tag/human_slug` (name) 
- la api de EventsViewSet debe recibir `tag` en lugar de `slug`
