### ISSUE TITLE
Posibilidad de forzar la aceptación del código de conducta durante la registración.

### ISSUE THREAD

**Issue by facundobatista** [eventoL/eventoL#379]
En el proceso de registración, al darse de alta una persona para un evento, debería tener un checkbox o similar con el que indique que "acepta el código de conducta del evento", más un link al código de conducta en cuestión (que puede ser cualquiera, lo más probable es que sea externo a eventol mismo).

Que esta indicación esté "aceptada" (checkbox clicked o similar) es condición indispensable para que el sistema deje registrar a la persona. En otras palabras, si no aceptás el código de conducta, no te registrás....

Gracias!

**Comment by FedeG** [comment]
Relacionada con #398
