### ISSUE TITLE
El formulario de registración siempre pregunta "is going to install"

### ISSUE THREAD

**Issue by gilgamezh** [eventoL/eventoL#385]
Debería preguntarlo únicamente en los eventos que son FLISOL.

Por otro lado con la implementación de "preguntas" podría eliminarse ese campo

**Comment by FedeG** [comment]
Relacionada con #398

**Comment by cmdelatorre** [comment]
Como inmersión al proyecto, estaba analizando este issue. Para ver si puedo hacer algo hasta que se resuelva todo el tema de "preguntas".

Entonces, acá se me ocurre que se puede atacar 

- haciendo más complejos los forms para que incluyan el field `is_installing` solo si el evento `is_flisol` (o sea del lado de Django). O,
- poniendo algo de JS y _frontend-magic_ para ocultar ese campo (y de paso también el botón de "REGISTER AS AN INSTALLER").

¿Tiene sentido o estoy orinando fuera del recipiente?
