### ISSUE TITLE
Problemas en el registro cuando no acepto compartir mis datos con los sponsors

### ISSUE THREAD

**Issue by javierverb** [eventoL/eventoL#432]
**Describe el error**
Se muestra la página de error 500 con el mensaje ' Algo, en alguna parte, salió terriblemente mal. Por favor, infórmanos! '

**Repoducción del error**
Pasos para reproducir el error:
1. Entrar a https://eventos.python.org.ar/events/pyconar2018/registration
2. Completar los datos
3. Desmarcar la casilla 'Aceptas compartir los datos de este formulario con los sponsors de la conferencia'.
4. Ver error

**Comportamiento esperado**
Esperaba ver el mensaje de confirmación de email.

**Capturas de pantalla**
https://screenshots.firefox.com/aEKWyX1meIur2Zup/eventos.python.org.ar
https://screenshots.firefox.com/H2cJs6LzBv0DVRLM/eventos.python.org.ar

**Escritorio (complete la siguiente información):**
  - OS: Ubuntu 16:04
  - Navegador: Firefox Quantum 64-bits
  - Versión:  62.0.3

**Comment by FedeG** [comment]
@javierverb Gracias por reportarlo y dar tantos detalles.
El problema era un tema de configuración del evento.
Ya esta solucionado.
