### ISSUE TITLE
Change date format in index page

### ISSUE THREAD

**Issue by FedeG** [eventoL/eventoL#513]

**Comment by echeva** [comment]
Cree un evento con más de un día del mismo mes y la presentación resulta entendible.

Inglés: 
![imagen](https://user-images.githubusercontent.com/26970810/53699243-fe3ff700-3dc4-11e9-9e2e-77175a72febf.png)

Español:
![imagen](https://user-images.githubusercontent.com/26970810/53699252-0e57d680-3dc5-11e9-8a65-cd446735531f.png)
