### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by NathanBnm** [eventoL/eventoL#619]
Could you please add French on Weblate? I would like to contribute!

**Comment by FedeG** [comment]
@NathanBnm Yes, I can.
Today I'll add French language.

**Comment by NathanBnm** [comment]
Thanks! Please notify me when it's available 😄

**Comment by FedeG** [comment]
@NathanBnm do you prefer a specific French or neutral French?

French options:
```
fr | French
fr-BE | French (Belgium)
fr-CA | French (Canada)
fr-CH | French (Switzerland)
fr-FR | French (France)
fr-LU | French (Luxembourg)
fr-MC | French (Principality of Monaco)
```

**Comment by NathanBnm** [comment]
I'm from France so neutral French (fr) is fine

**Comment by FedeG** [comment]
@NathanBnm I added French language.

**Comment by NathanBnm** [comment]
@FedeG I have some trouble translating your app.
The `register` word is often used but it seems that it hasn't always the same meaning. Sometimes it means "to register to an event" for example, and sometimes it means "to register presence to an event". I don't know what to translate how depending of the context because it French it has not the same meaning. Can you help?

There are some translations I left blank on Weblate because I have no idea about what it means. Could you check and add comments to add context please?

**Comment by FedeG** [comment]
Yes, I can. I'll check on Weblate and add context.

**Comment by FedeG** [comment]
@NathanBnm I added context to all pending strings

**Comment by FedeG** [comment]
@NathanBnm I fixed all misspellings.
Thanks for your contribution.

**Comment by NathanBnm** [comment]
Thanks. I'll check that when I have time.

**Comment by NathanBnm** [comment]
@FedeG could you please add context to the strings which contains the word `register` or `registration` to make the difference between the event check-in and the event first registration?
