### ISSUE TITLE
Misspellings

### ISSUE THREAD

**Issue by NathanBnm** [eventoL/eventoL#624]
While translating your app into French I noticed there were some misspellings or inconsistencies. Here are the changes you should do.

In the `django.po` file (line numbers are refering to the unstranslated file)

Line 222
```diff
-msgid "Custom css"
+msgid "Custom CSS"
```
Line 523
```diff
-msgid "Tell us about you (we will user it as your \"bio\" in our website"
+msgid "Tell us about you (we will use it as your \"bio\" in our website"
```

Line 906
```diff
-msgid "Export to csv"
+msgid "Export to CSV"
```

Line 924 (should be like line 505)
```diff
-msgid "Start"
+msgid "Start Time"
```
Line 927  (should be like line 508)
```diff
-msgid "End"
+msgid "EndTime"
```

Line 1113 (I think you forgot to translate this in English)
```diff
-msgid "Organizadores"
+msgid "Organisators"
```

Line 1171
```diff
-msgid "Please provide a abstract about your event"
+msgid "Please provide an abstract about your event"
```

Line 1180 (Using two exclamations is not correct, it should be on or three)
```diff
-msgid "Draw!!"
+msgid "Draw!"
```

Line 1291
```diff
-msgid "Register a Attendee"
+msgid "Register an Attendee"
```

Here it seems that the HTML is broken (not detected by Weblate):
![image](https://user-images.githubusercontent.com/45366162/72434433-e33b6300-379b-11ea-9ab4-f61df9c176cb.png)

I hope you can do these little fixes 😄

**Comment by FedeG** [comment]
@NathanBnm I'll fix those misspellings.
About the HTML, this HTML is the template of email that EventoL send to the attendees

**Comment by FedeG** [comment]
@NathanBnm I fixed all misspellings.
Thanks for your contribution.

**Comment by NathanBnm** [comment]
@FedeG the html have one tag `</p>` more than the number of `<p>` tags. I thought it was an error

**Comment by NathanBnm** [comment]
@FedeG with the context you added I reopen this.

In `djangojs.po`

Line 46:
```diff
-msgid "Search by title..."
+msgid "Search by title…"
```
Note: Everywhere in your project you should use the ellipsis symbol (…) instead of three detached dots.

Line 151:
```diff
-msgid "Don't configured"
+msgid "Not configured"
```

Line 202:
```diff
-msgid "Reconecting websocket, attemps"
+msgid "Reconnecting websocket, attempt"
```
