### ISSUE TITLE
Missing volumes files for docker containers.

### ISSUE THREAD

**Issue by Bgeninatti** [eventoL/eventoL#642]
**Describe the bug**
I'm having an issue loading the dev environment.
While running the command ```make deploy-dev```

1. The step ```cd deploy/docker && docker-compose build --force-rm``` run without errors.
2. The step ```cd deploy/docker && docker-compose up -d --remove-orphans```
Returns the following error:
```
docker_redis_1 is up-to-date
Creating docker_reactjs_1  ... error
Creating docker_postgres_1 ... 

Creating docker_postgres_1 ... error

ERROR: for docker_postgres_1  Cannot create container for service postgres: invalid mount config for type "bind": bind source path does not exist: /home/fly/repos/eventoL/deploy/docker/db/postgres

ERROR: for reactjs  Cannot create container for service reactjs: invalid mount config for type "bind": bind source path does not exist: /home/fly/repos/eventoL/eventol/front/webpack-stats-local.json

ERROR: for postgres  Cannot create container for service postgres: invalid mount config for type "bind": bind source path does not exist: /home/fly/repos/eventoL/deploy/docker/db/postgres
ERROR: Encountered errors while bringing up the project.
make: *** [Makefile:187: deploy-dev] Error 1
```

I noticed that the missing files (```eventoL/deploy/docker/db/postgres``` and ```eventoL/eventol/front/webpack-stats-local.json```) refer to container volumes in the ```eventoL/deploy/docker/docker-compose.yml``` file, but couldn't figure out why the files are not there.

Only the docker_redis_1 container is running: 
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
2af890c0b2e5        redis:4.0.2         "docker-entrypoint.s…"   About an hour ago   Up About an hour    6379/tcp            docker_redis_1
```

**To Reproduce**
1. clone master branch.
2. execute make deploy-dev
3. See error while running the command ```cd deploy/docker && docker-compose up -d **--remove-orphans```
4. Check that cointarines docker_postgres_1 and docker_reactjs_1 are not running.

**Expected behavior**
Docker compose should run the already build containers docker_postgres_1 and docker_reactjs_1.

**Desktop:**
```
$ uname -a
Linux trantor 5.5.13-arch2-1 #1 SMP PREEMPT Mon, 30 Mar 2020 20:42:41 +0000 x86_64 GNU/Linux
$ docker --version
Docker version 19.03.8-ce, build afacb8b7f0
$ docker-compose --version
docker-compose version 1.25.4, build unknown
```

**Additional context**

I found [this similar issue](https://github.com/eventoL/eventoL/issues/633) but don't think is related. In my case zlib is installed.
The steps to reproduce the error are the same, but the error is different, and I'm using Arch instead of Debian.

**Comment by FedeG** [comment]
I´ll add `mkdir -p` and `touch` to **Makefile** commands to create these folders and files when they don´t exist
