### ISSUE TITLE
Makefile commands raises errors for dev environment setup.

### ISSUE THREAD

**Issue by Bgeninatti** [eventoL/eventoL#643]
**Describe the bug**

In the Makefile the command `migrate` (that refers to `docker-backend-migrate`) is executed with `${DOCKER_COMPOSE_PROD}` and returns the following error:
```
$ make migrate
cd deploy/docker && docker-compose -f docker-compose.prod.yml exec -T worker make backend-migrate
ERROR: The Compose file './docker-compose.prod.yml' is invalid because:
services.nginx-proxy.ports contains an invalid type, it should be a number, or an object
make: *** [Makefile:236: docker-backend-migrate] Error 1
```

The same happens with commans: `collectstatic` and `runserver`

**To Reproduce**
1. clone the `develop` branch
2. After run `make deploy-dev` execute `make migrate`
3. See the error

**Expected behavior**
That the command be executed without errors.

**Desktop:**
```
$ uname -a
Linux trantor 5.5.13-arch2-1 #1 SMP PREEMPT Mon, 30 Mar 2020 20:42:41 +0000 x86_64 GNU/Linux
$ docker --version
Docker version 19.03.8-ce, build afacb8b7f0
$ docker-compose --version
docker-compose version 1.25.4, build unknown
```

**Comment by Bgeninatti** [comment]
If the commands are executed with `${DOCKER_COMPOSE}` instead of `${DOCKER_COMPOSE_PROD}`, it works OK.

**Comment by Bgeninatti** [comment]
The same happens with the following commands:

* `restart`
* `compile-translations`

Is there some reason to have any reference to DOCKER_COMPOSE_PROD in a Makefile for development? 

If not maybe we can just use the name DOCKER_COMPOSE, comment/uncomment the correct line for prod or dev in the Makefile and document it in that way.

**Comment by FedeG** [comment]
The error `services.nginx-proxy.ports contains an invalid type, it should be a number, or an object` is that the `docker-compose.prod.yml` file use `EXTERNAL_PORT` for **nginx-proxy** service.
I´ĺl add a default value to **Makefile** to fix it
