### ISSUE TITLE
Cambiar el Captcha

### ISSUE THREAD

**Issue by eamanu** [eventoL/eventoL#654]
Se podría cambiar el captcha por algún que tenga audio. Durante la organización
de Flisol de la Rioja 2020, tenemos un expositor con otras capacidades (diminución de
la visión) que  va a exponer sobre accesibilidad. Y me mostró que no puede realizar la
carga de una propuesta, ya que tiene un captcha sin sonido, por lo que él no puede
proponer una charla. 

**Describe la solución que te gustaría**
Cambiar el captcha por alguna que tenga sonido

![image](https://user-images.githubusercontent.com/7605307/82852051-1921ee00-9ed8-11ea-838d-c21b4f857aa3.png)

**Comment by FedeG** [comment]
Para la próxima release vamos a arreglar este error.

Si bien hay un bot de accessibility no detecto este error porque corre sobre el código sin ejecutar, pero vamos a incorporar testing automatizado de accessibility (ya hay algunas pruebas de concepto con https://pypi.org/project/axe-selenium-python/) aunque no creo que detecte este problema va a avisar otros errores relacionados.

**Comment by FedeG** [comment]
Dejo mas contexto.
Actualmente usamos el modulo https://pypi.org/project/django-simple-captcha/ que tiene opciones para sonido.
Dejo link de la documentación oficial sobre las opciones de sox y flite: https://django-simple-captcha.readthedocs.io/en/latest/advanced.html?highlight=audio#captcha-sox-path

**Comment by marcorichetta** [comment]
Agrego acá un issue planteado en el sitio de pyar que es muy similar https://github.com/PyAr/pyarweb/issues/479

La `v0.5.12`, que es la que se usó en pyar, es compatible con eventol.
