### ISSUE TITLE
No se pueden expandir las actividades propuestas

### ISSUE THREAD

**Issue by manuq** [eventoL/eventoL#794]
**Describe el error**
Al intentar expandir la actividad propuesta haciendo click en la flecha hacia abajo, no ocurre nada. En la consola de javascript aparece el siguiente error:
![Captura de pantalla de 2022-04-06 18-49-16](https://user-images.githubusercontent.com/83944/162078024-c00041da-1603-49be-abab-7547fea19986.png)

Evidentemente el texto está ahí en el HTML, pero oculto:
![Captura de pantalla de 2022-04-06 18-51-46](https://user-images.githubusercontent.com/83944/162078269-ab6fc11e-e194-4534-9bb3-a99f37734890.png)

**Comment by FedeG** [comment]
Hice algunas pruebas en instancias actualizadas y esto funciona correctamente, puede se una cuestión de la versión del servidor.
El día viernes se va a actualizar, voy a probar nuevamente en esa fecha

**Comment by FedeG** [comment]
@manuq ya lo probé en la instancia actualizada y funciona. Espero igual tu confirmación para cerrar el issue

**Comment by manuq** [comment]
> @manuq ya lo probé en la instancia actualizada y funciona. Espero igual tu confirmación para cerrar el issue

Sí! Se resolvió al actualizar, gracias!
